### ISSUE TITLE
Underscore not escaped

### ISSUE THREAD

**Issue by jgollenz** [yegor256/iexec#7]
`\iexec[stdout=foo.txt]{echo $MY_VAR}`

will result in 

```
unhbox voidb@x protect penalty @M hskip z@skip T1textunderscore protect discretionary {char hyphenchar font }{}{}protect penalty @M hskip z@skip VAR
```

A shell variable is not my actual use case, I'm trying to use `jq` and the json key also contains an underscore. Unfortunately I have no experience with writing latex plugins, so I'm having a hard time figuring out how to fix this. I saw [this escaping](https://github.com/yegor256/iexec/blob/35c344090ae89f7d828945b11f1e26bc00e867e2/iexec.sty#L51) and tried to append something like `\let\__%`, but no avail.

**Comment by yegor256** [comment]
@jgollenz see 0582fd4 and f66fd29 The test works for me.

**Comment by yegor256** [comment]
@jgollenz maybe the problem is related to the fact that you don't use `quiet` option and the result of execution gets imported into your document. This text may have some issues, that's why your compiler complains.
